"""alter babaies tables

Revision ID: 84ada865297d
Revises: 302ccb04e147
Create Date: 2026-04-16 17:09:56.479313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ada865297d'
down_revision = '302ccb04e147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('babies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('babies', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
